# Generated by Django 2.1.7 on 2019-03-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('media_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Voice Posts',
                'verbose_name': 'Voice Post',
            },
        ),
    ]
